:bookseries: radar

= Impact of Open Source on Growth, Jobs, and Prosperity of Small Businesses: A Case Study 
Mike Hendrickson, Roger Magoulas, Kathryn Barret 
 
== Executive Summary 

By most traditional measures, pure-play open source companies appear to have had a relatively modest economic impact. Red Hat, the largest open source software company, had revenues of $1.13B for the fiscal year ending February 29, 2012, and a market capitalization of $10.8B as of June 2012. MySQL was sold for $1B to Sun Microsystems in 2008. After the sale of Sun to Oracle, MySQL has estimated revenues in the range of $171M, and the MySQL ecosystem revenue is expected to grow at a CAGR of 40% to reach $664M by 2015 footnote:[http://blogs.the451group.com/information_management/2012/05/22/mysql-nosql-newsql/[Matthew Aslett 451 Research]]. There are a number of smaller pure-play open source companies, but none of them have achieved the scale of either of these two market leaders.

Yet there is no question that open source software has had a profound economic impact that belies these numbers. Companies like Google, Amazon, Facebook, and Twitter are built on open source platforms. All of them run on Linux, make heavy use of open source databases and languages, and contribute to the open source communities they rely on. They have built a proprietary layer on top of the open source stack, but can be thought of as applications on the open source platform in the same way that Mac OS X, iPhone, or iPad applications are built on the Apple platform, or Windows applications on the Microsoft platform.

And the economic impact is clear: Google had 2011 revenues of $37.9B and market capitalization of $189B. Facebook sports revenues of $3.8B and market cap of $82B, and Amazon has revenues of $51B and a market cap of $103B. But because open source software is not monetized directly by these companies, it tends to disappear from economic analysis.

In 1975, environmentalist Steve Baer described in his book _Sunspots_ (Zomeworks) this kind of indirect economic impact by way of an analogy he referred to as the "Clothesline Paradox" (<<clothesline>>): If you take down your clothesline and buy an electric clothes dryer, the electric consumption of the nation rises slightly. If you go in the other direction and remove the electric clothes dryer and install a clothesline, the consumption of electricity drops slightly, but there is no credit given anywhere on the charts and graphs to solar energy, which is now drying the clothes.

So too it is for the Web. Tim Berners-Lee put the Web into the public domain, the most open of all open source licenses; as a result, like the ecosystem services provided by the sun, open source software disappears from our accounting.

It is difficult to know how much value to ascribe to the open source platforms of the Web, of Linux, of MySQL, and of open source programming languages and tools in the success of companies like Google, Amazon, and Facebook because of the large admixture of proprietary software and services.

Fortunately, there is another market in which open source software is more directly delivered as a service. Internet service providers, domain name registrars, and web hosting firms effectively sell access to open source software for a monthly subscription fee.
// this is a comment
In this report, we provide an analysis of the economic impact of open source software on the success of these industries, and by extension, on the businesses they serve. In particular, we focus on web hosting, which provides websites and ancillary services to small and medium sized businesses (SMBs).

