:bookseries: radar

= Impact of Open Source on Growth, Jobs and Prosperity of Small Businesses: A Case Study 
Mike Hendrickson, Roger Magoulas, Kathryn Barret 
 
== Executive Summary 

By most traditional measures, pure play open source companies appear to have had a relatively modest economic impact.  Red Hat, the largest open source software company, had revenues of $1.13B for the fiscal year ending February 29, 2012, and a market capitalization of 10.74B as of June 2012.  MySql was sold for $1 billion to Sun Microsystems in 2008? and after the sale of Sun to Oracle, has estimated revenues in the range of $171m and MySQL ecosystem revenue is expected to grow at a CAGR of 40% to reach $664m by 2015 footnote:[http://blogs.the451group.com/information_management/2012/05/22/mysql-nosql-newsql/[Matthew Aslett, the451group]]. There are a number of smaller pure play open source companies, but none of them have achieved the scale of either of these two market leaders.

Yet there is no question that open source software has had a profound economic impact that belies these numbers. Companies like Google, Amazon, Facebook, and Twitter are built on open source platforms. All of them run on Linux, make heavy use of open source databases and languages, and contribute to the open source communities they rely on. They have built a proprietary layer on top of the open source stack, but can be thought of as applications on the open source platform in the same way that MacOS x, iPhone, or iPad applications are built on the Apple platform, or Windows applications on the Microsoft platform.

And the economic impact is clear:  Google had 2011 revenues of $37,905B and market capitalization of $188.60B. Facebook sports revenues of $3.8B and market cap of $82.2B, and Amazon $48.08 and a market cap of $102.88B. But because  open source software is not monetized directly by these companies, it tends to disappear from economic analysis.

This is a variation of what solar activist Steve Baer called "the
clothesline paradox" in his 1975 book Sunspots

1n 1975, environmentalist Steve Baer described, in his book Sunspots, this kind of indirect economic impact by way of an analogy he referred to as the Clothesline Paradox: If you take down your clothesline and buy an electric clothes dryer, the electric consumption of the nation rises slightly. If you go in the other direction and remove the electric clothes dryer and install a clothesline, the consumption of electricity drops slightly, but there is no credit given anywhere on the charts and graphs to solar energy, which is now drying the clothes.

So too it is for the web. Tim Berners-Lee put the web into the public domain, the most open of all open source licenses; as a result, like the ecosystem services provided by the sun, open source software disappears from our accounting.

It is difficult to know how much value to ascribe to the open source platforms of the web, of Linux, of MySql, and of open source programming languages and tools in the success of companies like Google, Amazon, and Facebook because of the large admixture of proprietary software and services.

Fortunately, there is another market in which open source software is more directly delivered as a service. Internet Service Providers, Domain Name Registrars, and Web Hosting firms effectively sell access to open source software for a monthly subscription fee.

In this report, we provide an analysis of the economic impact of open source software on the success of these industries, and by extension, on the businesses they serve. In particular, we focus on web hosting, which provides web sites and ancillary services to small and medium sized businesses.

Sources needed: stats on overall size and revenues of ISP business, web hosting, Bluehost as a share of that. Domain registration too.

If possible, would be interesting to compare revenues of these segments to the signature companies listed above. This would give us a sense of the innovation premium vs the base case value of open source.

