= Open Source Sweeping Impact on Growth, Jobs and Prosperity of Small and Medium Businesses

Mike Hendrickson
Andy Oram
Roger Magoulas

== Executive Summary


In the US, a small business can be classified as one that is organized for profit; has a place of business in the U.S.; operates primarily within the U.S. or makes a significant contribution to the U.S. economy through payment of taxes or use of American products, materials or labor; is independently owned and operated; and is not dominant in its field on a national basis. The business may be a sole proprietorship, partnership, corporation, or any other legal form.  Other countries have similar definitions of what small business constitutes.  For the purpose of this report we are going use the preceding definition.  Small businesses vary widely though. Use of the internet seems to drive small business quicker than other factors.  On average, small businesses see an 10% increase in productivity from internet usage*, and grow and export twice as much as small businesses not using the internet.  Some have compared the internet's impact with the Guttenberg press, yet it is more analogous to the advent of electricity on our global economy.  On a global scale, internet penetration is linked with reducing poverty while encouraging small business development.  So many small businesses that are getting going turn to the internet as a means to their financial goals.  But what technologies are these small companies using?  How are they making the internet work for them?  Are they driving the internet or are the large behemoths?  

This Radar Report will shed light on the smalls businesses using Open Source technologies to help them grow, prosper and contribute to the world around them.  The Report includes data from our Jobs data-mart, Google trends, retail book trends and some general scraping and collecting of internet data to surface any trends surrounding the current State of the Web Performance Optimization market. Closely related to WPO is Web Operations that basically ensures that your fast performing web property will continue to deliver 24x7. And even though web operations is closely related to WPO, we are not going to focus on that discipline in this report. So let's take a look at the growth of the Web and the new burgeoning discipline of Web Performance Optimization - WPO.

If you figure that the global average connection speed is 2.3 Mbps and the global average peak connection speed is 11.7 Mbps*1, how fast will web sites need to be effectively serve data at the peak rate or to satisfy the connection rate lower end of the speed scale. 

=== Nice Chart of overall market. 


If you figure that the global average connection speed is 2.3 Mbps and the global average peak connection speed is 11.7 Mbps*1, how fast will web sites need to be effectively serve data at the peak rate or to satisfy the connection rate lower end of the speed scale. 

