:bookseries: radar

= Impact of Open Source on Growth, Jobs, and Prosperity of Small Businesses: A Case Study 
Mike Hendrickson and Roger Magoulas
 
== Introduction

By most traditional measures, pure-play open source companies appear to have had a relatively modest economic impact. Red Hat, the largest open source software company, had revenues of $1.13B for the fiscal year ending February 29, 2012, and a market capitalization of $10.8B as of June 2012. MySQL was sold for $1 Billion to Sun Microsystems in 2008. After the sale of Sun to Oracle, MySQL has estimated revenues in the range of $171M, and the MySQL ecosystem revenue is expected to grow at a CAGR of 40% to reach $664M by 2015 footnote:[http://blogs.the451group.com/information_management/2012/05/22/mysql-nosql-newsql/[Matthew Aslett 451 Research]]. There are a number of smaller pure-play open source companies, but none of them have achieved the scale of either of these two market leaders.

Yet there is no question that open source software has had a profound economic impact that belies these numbers. Companies like Google, Amazon, Facebook, and Twitter are built on open source platforms. All of them run on Linux, make heavy use of open source databases and languages, and contribute to the open source communities they rely on. They have built a proprietary layer on top of the open source stack, but can be thought of as applications on the open source platform in the same way that Mac OS X, iPhone, or iPad applications are built on the Apple platform, or Windows applications on the Microsoft platform.

And the economic impact is clear: Google had 2011 revenues of $37.9B and market capitalization of $189B. Facebook had 2011 revenues of $3.8B and market cap of $82B, and Amazon had 2011 revenues of $51B and a market cap of $103B. But because open source software is not monetized directly by these companies, it tends to disappear from economic analysis.

In 1975, environmentalist Steve Baer described in his book _Sunspots_ (Zomeworks) this kind of indirect economic impact by way of an analogy he referred to as the "Clothesline Paradox": If you take down your clothesline and buy an electric clothes dryer, the electric consumption of the nation rises slightly. If you go in the other direction and remove the electric clothes dryer and install a clothesline, the consumption of electricity drops slightly, but there is no credit given anywhere on the charts and graphs to solar energy, which is now drying the clothes.

So too it is for the Web. Tim Berners-Lee put the Web into the public domain, the most open of all open source licenses; as a result, like the ecosystem services provided by the sun, open source software disappears from our accounting.

It is difficult to know how much value to ascribe to the open source platforms of the Web, of Linux, of MySQL, and of open source programming languages and tools in the success of companies like Google, Amazon, and Facebook because of the large admixture of proprietary software and services.

Fortunately, there is another market in which open source software is more directly delivered as a service. Internet service providers, Domain name registrars, and web hosting firms effectively sell access to open source software for a monthly subscription fee.

According to IBIS Research (http://www.ibisworld.com/industry/default.aspx?indid=1901), the total size of the Internet Service Provider market in 2011 was $79 Billion. ISPs typically provide both a data pipe and a set of basic internet services, including email and web access.  They may also provide web hosting, and with it, domain name registration services. It is difficult to allocate revenues between simple data provisioning, access to free (but not open source) services such as Google, Facebook, YouTube, Twitter, and millions of websites, versus use of open source email and web tools, but there's no question that without the existence of the free and open source software of the Internet, this huge and profitable market would not exist.

(In an interesting example of the Clothesline Paradox, it's worth noting that while Internet users are often accused of enjoying free content, and being unwilling to pay for what they receive, they in fact typically pay substantial sums to their ISPs as a montly subscription for access to these "free" services. Simply by comparing the economics for the Cable companies and other ISPs for consumers who use Internet services to those who watch television, you can see that it is the ISP, not the consumer, who is getting the free ride. On the television side, the Cable service provider must pay for content; on the Internet side, they get it for free, with much of it provided by the very customers who are paying them for access.)

Since the domain registry market is simply a service based on the open source Berkeley Internet Name Daemon, or BIND, which (along with a few derivative programs) provides the internet's Domain Naming System, or DNS, it's fairly reasonable to ascribe the entire size of this market to open source software. In 2011, this market was $xx.  Dominant providers include GoDaddy, Tucows, ... mention ICANN as well?

The web hosting market is the segment that is most worthy of deeper analysis.  Web hosting firms (including the web hosting component of Internet Service Providers) effectively provide access not only to a web server but also to programming languages, content management systems, and other software components for which there are both proprietary and open source alternatives.

Fortunately, we have access to a unique data set provided by BlueHost, a web hosting company that provides hosting services to xx million sites in the US [worldwide?]  BlueHost is the nth largest hosting provider in the US, representing yy% of the hosting market.  They service primarily small and medium sized businesses (SMBs) and individuals.

In this report, we use the BlueHost data to project the total economic impact of open source software as an enabler of the web hosting market as well as the economic impact on the SMBs who make up its customers. We also analyze the actual software used by these customers, comparing the usage of proprietary versus open source alternatives, and estimating the cost savings provided by open source software.

In this report, we provide an analysis of the economic impact of open source software on the success of these industries, and by extension, on the businesses they serve. In particular, we focus on web hosting, which provides websites and ancillary services to small and medium sized businesses (SMBs).

