:bookseries: radar

== Open Source helps keep costs low enough for SMBs to participate
Small and medium sized businesses (SMBs) are faced with a dizzying array of open source and commercial options when choosing the software they need to run and grow their business. And US SMBs IT investments are expected to exceed 138B in 2012. footnote:[http://www.biztechreports.com/analyst_news__views/analys_news__views_archive_4132012[Justin Jaffe IDC]]  Somwhere around 25% of that on computer systems and support. Several sources have SMB IT spend on between 25% and 33% of all IT spending, and that it’s growing faster than for large enterprises and heading to the cloud and hosting due to personnel and cost factors.

For the SMBs heading to the cloud, the portion of SMBs IT budget spent on application hardware and software infrastructure, the servers, networking, operating system, web servers and data management tools, we developed a cost differential ratio: commercial products cost about twice as much as open source options [or open source options cost about half what the commercial products on the same hardware). there’s a subtle point here, for just the software, the differential is likely greater, e.g., if hardware, virtualization and networks represent 50% of what you’re paying for from Amazon, the price differential is more like Consider the formula a blunt instrument that provide an indication of cost saving available to SMBs when they consider technology options. We developed the formula using the technology choices for ecommerce, CMS and other applications discovered by analyzing nearly one million Bluehost customer preferences.

The price differential may be useful for comparing commercial and open source applications, however, resources, training, support and other factors may blunt the cost savings.

=== Methodology (simple):
Assumptions:

Bluehost users mix of ecommerce, CMS and web presence which represents a reasonable proxy for a US SMB market
Amazon EC2 pricing a reasonable proxy for the difference in open source and commercial server software infrastructure, i.e., operating systems
Average hours used / day: 18
Half of SMBs with ecommerce or transactions systems have small enough data volumes to use free versions of commercial databases, e.g., SQL Server Express (10 Gb limit)
Half of SMBs with CMSs have small enough data volumes to use free commercial databases

=== Methodology (detail):

For price differentials, use Amazon EC2 pricing for Linux and Windows, June 29, 2012 prices
Used Light Utilization Reserved Instance Pricing for 1 year term
most appropriate for looking at web presence, instance is always available, but only accumulates charges when used

Use 18 hours/day usage pattern; if full usage more economical to choose heavier use options
SMBs with a heavy web presence will choose Medium or High Utilization options to reduce hourly costs; formula shows a bigger markup for the Medium option
3% * 11.54 + 35% * 2.39 + 61% * 1.83 = 2.39
consider averaging the two? avg: 222%

For open source we used Linux pricing

For proprietary/commercial we used Windows pricing in three flavors:
. Windows Includes access to SQL Server Express and IIS; SQL Server Express is limited to 10 Gb of storage
. Windows with SQL Web Usage appropriate for CMS and other web support
. Windows with SQL Standard Usage Appropriate for ecommerce and other transaction systems

Took average of price differentials for Small and Medium Instances
Ecommerce share - based on share of Bluehost ecommerce customers as a share of all business customers who chose a business tool (ecommerce or CMS app) or had other signs of a business presence (domain + mailbox activity)

Ecommerce systems require a database for transactions, for the proprietary option we used SQL Server w/ full access

CMS share - based on share of Bluehost CMS customers as a share of all business customers who chose a business tool (ecommerce or CMS app) or had other signs of a business presence (domain + mailbox activity)

CMS systems rely on a database to store data, for the propietary options we used SQL Server w/ web access, if SQL Server Express, which is free w/ the standard Windows EC2 package, then the price differential would be the same as for just Windows with no database
issues:

For many small businesses, SQL Server Express may have enough storage to be useful, reducing the need for the costlier web and full-use database options, consider multiplying the share for CMS and eCommerce by 50%
see spreadsheet ~/analysis_projects/bluehost_study/briefs/economic_impact.xls for details

==== Blunt model showing with an estimate of economic impact
Notes:
Per Jared, skip domain test, use 80% of joomla and drupal as business users, use 60% of customers with no tool and a domain, if not pulled by other queries.
- use a step wise process to load bus users in a new table and label them: ecom, cms, email. (Need % for cost saving analysis)

==== Low Cost Hosting Savings

. open source has kept comm'l sw prices low, savings would be more extreme if no competition
. consider look at cms mkt dominated by open source, need a platform share source

==== Example using Google Adwords to show impact

Web/Online presence pays off (Ben’s model showing Google leverage)
Point #3: Spending on Google AdWords work best if users go to a landing page, with a clear call-to-action. In addition, having a web site allows SMB owners to conduct simple A/B tests to increase conversion rates. Assuming that the average SMB owner who controls their own landing pages is able to meet Google's "conservative estimate" ( 8 * (what you spend on AdWords) )
(5.4 billion in 2010 ad spending) * (29% of ad spending goes to Google AdWords) * (47% of SMB's without their own web site) * 8 =  $6 billion dollars of economic benefit lost, because companies don't have a web site,
Assumption 29% of ad spending goes to Google AdWords)
* 2008 eMarketer Report, estimated that by 2012, 37% of online ad spend will go to paid search   http://www.emarketer.com/Reports/Viewer.aspx?R=2000488&page=5 [online ad spend]
* Google owns 80% of ad spend on paid search    http://www.advmediaproductions.com/blog/google-dominates-paid-search-advertising-with-80-market-share-unaffected-by-the-rise-of-bing/ [paid search]
*      37% * 80% = 29.6%
Made possible by lower costs (and virtualizations)
Constant pressure on costs the last 15 years from open source projects has made a web presence affordable, and the business opportunities a web presence provides, possible for many SMBs, including the growing Home Based Business (HBB) segment
Commercial vendors need to keep prices in check due to competition from open source projects
In some applications spaces important to SMBs, e.g., eCommerce platforms and CMS systems, open source tools have become significant share
For SMBs, virtualization and hosting provide access to technology skills and more efficient resource utilization (i.e., “sharing” a server) that also enable lower costs and wider access to a web presence (not related to open source, but a worthwhile point)
Looking at last few years, we build a model showing the cost differential created by Open Source options for the software infrastructure for creating a web presence

=== Small Business Should be Online
Open Source helps keep costs low enough for SMBs to build web presence for promotions, advertising and displaying company/product information
Blunt model showing with an estimate of economic impact
Low Cost Hosting Savings
open source has kept comm'l sw prices low, savings would be more extreme if no competition
consider look at cms mkt dominated by open source, need a platform share source
Other sources of open source economic impact for small business: eBay, etsy, Facebook, Twitter
eBay and etsy as low cost, low friction marketplaces run on open source archictures
Facebook and Twitter as low/no cost promotion, social media and ad platforms that run on open source architectures 
Web presence provides chance to leverage ad networks
Example using Google Adwords to show impact of being online as economic lift
<not sure where to put: relate economic impact and ad impact to Bluehost customer base>
These are popular tools

=== Economic Impact

Open Source Savings Factor Formula:
Open Source Market Share

Consider two or three scenarios: 25% share, 50%, optionally 75% share
or just use the number for leverage

formula

<simple terms>
Use the mix of user tools in the Bluehost user data to allocate share to different workloads with different cost differentials, using Amazon EC2 pricing.

adjusted ecommerce share** (3%) * proprietary software cost differential (full db) (9.72)
+ adjusted CMS share** (35%) * proprietary software cost differential web database (2.13)
+ web presence (61%) * proprietary software cost differential (1.51)

3% * 9.72 + 35% * 2.13 + 61% * 1.51 = 2.05

==== Open Source Market Share
 


Factoids
81% of SMB company bosses prefer to research products over the internet before purchase (Serif)
contrast w/ action that a smaller percentage of SMBs have a web presence
http://webcache.googleusercontent.com/search?q=cache:3aU31xc7tp0J:www.microsoft.com/business/en-gb/Content/Pages/news.aspx%3Fcbcid%3D1043+smb's+without+a+web+site&cd=4&hl=en&ct=clnk&gl=us&client=safari [percent of smbs]
Recession speeds Linux adoption as firms lower costs, not deployments
http://www.waterandstone.com/open-source-cms-resources/articles/smaller-budgets-not-smaller-deployments [linux in recession]
40% of SMB plan to use social media in 2012, 25% expressed discomfort w/ using social tools; social networks for affordability, access to customers, referrals
http://www.zoomerang.com/uploadedFiles/docs/smb-business-perspective-2011-and-2012.pdf [business perscpective]

==== Facts and Sources
SMB Online Presence
40% of SMBs have no web site
Mar/2012 survey of 1&1 internet
http://www.transmutationsciences.com/design/smbs-without-websites-are-you-one-of-the-40-percent/ [40% not online]

FYI.  transmutationsciences and 1&1 Internet are both hosting companies reporting on their survey.  Do we really want to use a survey of a competitor to Bluehost in this?  Just asking.


Drawback
1&1 Internet is another “cheap” hosting site and may be viewed as a Bluehost competitor and may not want them referenced in the study
54% of SMBs have no online portal (UK data)
Serif Press Release July 15, 2011
http://www.serif.com/Press/PressReleases/2011/15072011.html
According to research conducted by software developer Serif, just 46 per cent of such enterprises have invested in their own online portal, reports PC Advisor.
survey of 400 small businesses in the UK

UK data. Our data is roughly 90% US and Canada. This seems like a stretch too.

30% of SMBs have no online presence
Parallels Cloud Service Provider Blog
http://blogs.parallels.com/serviceprovider/month/may-2012 [service providers]
Rough estimate of SMBs with no web site: average(40%, 54%, 30%) = 41%, or w/out UK data: average(40%, 30%) = 35%

I think this will work.

==== Web hosting costs
The average SMB spends $45/month on web hosting

Bluehost customers average rate of $7.49 per month so does mean anything

The average respondent without an online presence guessed that a business Web site would cost $67 per month, according to the study, while 91 percent of respondents guessed it would cost more than $10 per month.  According to the study, the average SMB with an online presence spends $45 per month for Web hosting.
Mar/2012 survey of 1&1 internet
http://www.transmutationsciences.com/design/smbs-without-websites-are-you-one-of-the-40-percent/ [smb web usage]

==== SMB IT Spending
$138B, $38B on IT Services (from an IDC report) for 2012
http://www.eweek.com/c/a/Midmarket/Tablet-Software-Purchases-to-Drive-SMB-IT-Spending-in-2012-IDC-281131/ [tablet purchases]
$154.6B US Small Business ICT Spend (AMI Partners)
http://www.ami-partners.com/downloads/isignal_Q1-2011.pdf [downlads]

==== Business counts by year, state size:
http://www2.census.gov/ces/bds/firm/bds_f_iszst_release.csv [census data]
smb/census_size_state_firms.csv [state census]

Now that we have spent a little time looking at the economics open source can have on a small business, let's not take a look at the technology stack they use, and the typical site owner profile.