:bookseries: radar

== Economic Impact of Open Source

SMBs receive many benefits from a web/online presence - benefits enabled by the low-cost Open Source infrastructure that girds the technology behind that presence. In this report, we'll look at how SMBs gain top-line customers and revenue from their web/online presence and how Open Source helps keep the web accessible for SMBs, including the growing Home-Based Business (HBB) segments.

// as alt to next two paragraphs

For SMBs, a web/online presence pays off immensely. In this report, we'll look at some of the factors leading to this pay off, and demonstrate how having a web presence makes such a significant difference, and how the use of Open Source is an additional driver for success. 

Constant downward cost pressures during the last 15 years from open source projects has made having a web presence affordable, and the business opportunities that a web presence provides are now more reachable for more if not all SMBs, including the growing home-based business (HBB) segment. 

So let's assume that a SMB uses Google AdWords to help boost their revenue. We know that spending on Google AdWords work best if users go to a landing page with a clear call to action. In addition, having a website allows SMB owners to conduct simple A/B tests to increase conversion rates. Assuming that the average SMB owner who controls their own landing pages is able to meet Google's _conservative estimate_ ( 8 * (what you spend on AdWords) ). So what does this mean when you aggregate all SMBs that have a web presence, or more importantly, those that do not have a presence are losing potential huge revenue gains. So let's look at a formula that could help us get more insight into the revenue gains or losses due to a web presence. Note that we are not covering the 70% of SMB online ad spend not used for Google Adwords - clearly SMBs get some value for these investments that increase the economic impact beyond the calculations we show below.

'(Total ad spending by SMBs)
       * (share of ad spending on Google AdWords)
       *  8 (this is the Google multiplier: $1 of ad spending => $8)
  = Economic impact of Google AdWords'

Next we estimate the dollars that _could_ have gone to SMBs that don’t have a website. Let’s look at each of these parts:

// following is a test

In::

Lorem::

Here's a test of a simple indent that one hopes spans two lines of display in the HTML view, I'm also hoping to test double indent::

next level of indent


1. List item one.
+
List item one continued with a second paragraph followed by an
Indented block. Now I'm testing how the indent wrap works by adding a long text phrase the will surely run past two lines
+
.................
$ ls *.sh
$ mv *.sh ~/tmp
.................
+
List item continued with a third paragraph.

2. List item two continued with an open block.
+
--
This paragraph is part of the preceding list item.

a. This list is nested and does not require explicit item continuation.
+
This paragraph is part of the preceding list item.

b. List item b.

This paragraph belongs to item two of the outer list.
--

[start=1]
. *Total ad spending by SMBs* => average of these two
$5.4 billion in 2010, according to this article from BIA/Kelsey. footnote:[http://www.biakelsey.com/Company/Press-Releases/110830-Digital-Advertising,-Performance-and-Retention-Solutions-Will-Be-70-Percent-of-SMB-Marketing-Budgets-by-2015.asp[BIA/Kelsey]]
+
$2,300 * # of SMBs in 2011. This survey estimates _online_ ad spend at $2,300 per SMB in 2011.

[start=2]
. *Share of ad spending on Google AdWords* ~29%. This is a product of the numbers below.
By 2010, 37% of online ad spending will go to paid search. footnote:[http://www.emarketer.com/Reports/Viewer.aspx?R=2000488&page=5[eMarketer]]
+
Google owns 80% of ad spend on paid search. footnote:[http://www.advmediaproductions.com/blog/google-dominates-paid-search-advertising-with-80-market-share-unaffected-by-the-rise-of-bing/[ADV Media]]
+
37% * 80% = 29.6%

[start=3]
. *Google multiplier = 8* footnote:[http://www.google.com/economicimpact/methodology.html[Google]]. We conservatively estimate that for every $1 a business spends on AdWords, it receives $8 in profit through Google Search and AdWords. Thus, to derive the economic value received by advertisers, we multiply our AdWords revenue on Google.com search results in 2011—what advertisers spent—by 8.

  ** Google owns 80% of ad spend on paid search. footnote:[http://www.advmediaproductions.com/blog/google-dominates-paid-search-advertising-with-80-market-share-unaffected-by-the-rise-of-bing/[ADV Media]]

Finally, we estimate what was _left off the table_. We estimate that as follows: 

'(# of SMBs without a website )
   * ( EconImp_Goog_SMB  /   # of SMBs with a website )
= (AdWords economic impact left on the table)'

This is an estimate, because we are assuming that EconImp_Goog_SMB came solely from SMBs with websites. (You still can use AdWords even if you don’t have a website, but you probably need to be able to optimize your landing pages to maximize conversion and get to the 8 multiple from Google.)

While we estimate the overall impact of one online ad channel, we know that SMBs have access to niche and specialized promotional platforms. From the CocoKnits case study, we see an SMB that uses the web ecosystem around the online knitting community to promote the business. Julie Weisenberger, the CocoKnits founder, thinks that "everyone who knits knows CocoKnits," via her own web site and the online knitting community (centered aroud web sites like Revelry) and that she doesn't need to use Google Adwords to add customers - an example of the hidden economy at work, no money changing hads, but great value from a web presence and a niche online community.

=== Open Source Cost Differential

The price for a web presence has been driven down for more than a decade by a number of factors, including resource sharing, enabled by virtualization, Moore's Law lowering the cost and increasing the power of compute resources, data center economies of scale, and, as we cover below, the availability and adoption of no-cost/low-cost open source projects as key web presence components. These lower costs have made a web presence, and all the benefits that a web presence provides, available to a wide swath of SMBs, and, for the growing HBB segment.

Open source projects and vendoes provide low-cost/no-cost options for business consumers, and, often, help keep the price of competing commercial products in check. For some tools relevant to SMBs, for example ecommerce and CMS, (rm note 2012-07-05: not sure where first reference and explanation of CMS resides in doc, I assume it's before this section end rm note) open source projects and vendors dominate the market.

For tech savvy SMBs, open source offers other benefits in addition to low cost: access to the source code, including the ability to make changes specific to your business, and access to community-based support. There are many stories of open source tool users posting a problem to an online forum and having the developer who wrote the code respond with a fix.

Keep in mind that beyond creating their own web presence, SMBs and HBBs have access to number of commerce platforms and marketing/promotion platforms that are built on open source architectures, for example: eBay, Amazon, Etsy, Google, Facebook, Twitter and Paypal. Even those SMBs with who build their own web presence may include storefronts on eBay, Amazon or Etsy, and may augment their marketing via Facebook and Twitter. We focus on the cost differential between between open source and commercial infrastructure components for SMBs running their own web presence, either on their own or via a hosting or cloud vendor. Later in this report, we talk about the impact of the large selling platforms and their potential impact on SMBs.

==== Open Source Savings Differential Model

We set out to build a model to help quantify the open source savings differential for infrastructure software like operating systems and databases - the type of infrastructure the undergirds most applications. We start by using Amazon's EC2 hosted platform pricing, with its open source (Linux, MySQL) and commercial (Microsoft Windows and SQL Server) options running on the same hardware platforms in the same data centers with the same tiered pricing options. We use an analysis of Bluehost's business customers to help us determine the share of SMB users likely to need a database - an extra cost item - based on their use of SMB applications like ecommerce and Content Management Systems (CMS).

Our model shows that for a proxy of the SMB market, the price differential for hardware/software platforms running commercial software is about 2, i.e., SMBs would pay about double for the hardware/software infrastructure they need to operate online. For smaller SMBs, who either don't need a database or you can use free commercial options, like SQL Server Express, the differential is about 1.5.

We focus on the infrastructure components of operating systems and databases as they are commonly required for web presence, managing content and online stores, and they require similar administration and operating expense loads. For more complex applications, researchers have found more of a mixed picture regarding savings from open source applications (consider adding references to research here, consider adding that research is often funded by comm'l vendors). Tellingly, for the types of applications most SMBs need for a web presence, CMSs and ecommerce apps, open source options dominate the low-end of the market - all the leading applications operate on both Linux and Windows, and most of the leading CMSs run on both MySQL and SQL Server.

Here’s the high level view of the model:

     Share of SMB customers w/ full access db * full access db price differential

        + share of SMB customers w/ web access db * web access db price differential

        + share of SMB customers w/ no db * no db price differential'

//rm I’m having a hard time deciding whether anything high level about the model should be added here (above), maybe just some text with a reference to the model details: eg, “At a high level, the model looks at the share of SMBs who need full database access, need web database access or who don’t need web access (web presence only), all adjusted for the estimated share of SMBs with enough data volumes to incur a charge for commercial database licenses (> 10 Gb)”

At a high level, the model looks a the share of SMBs who need the various levels of database support available for Windows platforms on EC2 and multiplies that by the price differential between Windows and Linux pricing for the types of EC2 instances appropriate for SMBs web presence. You can find more detail about the methodology and the assumptions used to develop the model in the appendix.